window.DEALS_DATA = {
  "metadata": {
    "title": "Reight Good Bikes - Multi-Source E-Bike Deals Hub",
    "last_updated": "2026-08-16 13:59:08",
    "total_deals": 24,
    "sources_scanned": [
      "E-BikeShop.co.uk",
      "Engwe UK",
      "Pure Electric",
      "Tenways",
      "Velotric"
    ],
    "categories": [
      "All",
      "Mega Deals",
      "Budget Steals",
      "Mountain",
      "Commuter",
      "Folding",
      "Cargo & Fat Tyre"
    ]
  },
  "deals": [
    {
      "id": "e_bikeshop_co_uk_15351321559424",
      "title": "Haibike Hybe CF 9 2026",
      "brand": "Haibike Electric Bikes",
      "retailer": "E-BikeShop UK",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Mountain",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 80,
      "motor_power": "250W-500W High Torque",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 6549,
      "sale_price": 4599,
      "savings_amount": 1950,
      "discount_percentage": 30,
      "image": "https://cdn.shopify.com/s/files/1/0609/4838/1934/files/Haibike-Hybe-CF-9-2026-Electric-Bike-Brown.jpg?v=1765810730",
      "url": "https://www.e-bikeshop.co.uk/products/electric-bike-haibike-hybe-cf-9-2026",
      "badge_text": "SAVE £1950 (30% OFF)"
    },
    {
      "id": "engwe_uk_8391383548086",
      "title": "P275 SE Combo",
      "brand": "engwe uk",
      "retailer": "Engwe UK Official",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Cargo & Fat Tyre",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 70.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 2948,
      "sale_price": 1548,
      "savings_amount": 1400,
      "discount_percentage": 47,
      "image": "https://cdn.shopify.com/s/files/1/0627/1385/6182/files/P275_SE_1.jpg?v=1768809378",
      "url": "https://engwe-bikes-uk.com/products/engwe-p275-se-combo",
      "badge_text": "SAVE £1400 (47% OFF)"
    },
    {
      "id": "engwe_uk_8241398710454",
      "title": "P275 SE",
      "brand": "engwe uk",
      "retailer": "Engwe UK Official",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 46.8,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 1499,
      "sale_price": 799,
      "savings_amount": 700,
      "discount_percentage": 47,
      "image": "https://cdn.shopify.com/s/files/1/0627/1385/6182/files/P275SE_01_7f24b64d-face-433f-9bcc-1f87be91b8c3.jpg?v=1767074661",
      "url": "https://engwe-bikes-uk.com/products/engwe-p275-se",
      "badge_text": "SAVE £700 (47% OFF)"
    },
    {
      "id": "e_bikeshop_co_uk_15351339581824",
      "title": "Haibike AllMtn 4 2026",
      "brand": "Haibike Electric Bikes",
      "retailer": "E-BikeShop UK",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Mountain",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 29.2,
      "motor_power": "250W-500W High Torque",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 4249,
      "sale_price": 3599,
      "savings_amount": 650,
      "discount_percentage": 15,
      "image": "https://cdn.shopify.com/s/files/1/0609/4838/1934/files/Haibike-AllMtn-4-2026-Electric-Bike-Grey.jpg?v=1765887983",
      "url": "https://www.e-bikeshop.co.uk/products/electric-bike-haibike-allmtn-4-2026",
      "badge_text": "SAVE £650 (15% OFF)"
    },
    {
      "id": "velotric_7528746451127",
      "title": "Velotric Fold 1 Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Folding",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 26.8,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1499,
      "sale_price": 1099,
      "savings_amount": 400,
      "discount_percentage": 27,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/F1_StoneGray_rightside1_1.png?v=1713178037",
      "url": "https://www.velotricbike.com/products/velotric-fold-1",
      "badge_text": "SAVE $400 (27% OFF)"
    },
    {
      "id": "e_bikeshop_co_uk_15351351247232",
      "title": "Haibike AllTrail 4 2026",
      "brand": "Haibike Electric Bikes",
      "retailer": "E-BikeShop UK",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Mountain",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 23.7,
      "motor_power": "250W-500W High Torque",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 3499,
      "sale_price": 2999,
      "savings_amount": 500,
      "discount_percentage": 14,
      "image": "https://cdn.shopify.com/s/files/1/0609/4838/1934/files/Haibike-AllTrail-4-2026-Electric-Bike-Blue.jpg?v=1765893898",
      "url": "https://www.e-bikeshop.co.uk/products/electric-bike-haibike-alltrail-4-2026",
      "badge_text": "SAVE £500 (14% OFF)"
    },
    {
      "id": "e_bikeshop_co_uk_15363969188224",
      "title": "Haibike AllTrack 6 2026",
      "brand": "Haibike Electric Bikes",
      "retailer": "E-BikeShop UK",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Mountain",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 22.5,
      "motor_power": "250W-500W High Torque",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 2949,
      "sale_price": 2499,
      "savings_amount": 450,
      "discount_percentage": 15,
      "image": "https://cdn.shopify.com/s/files/1/0609/4838/1934/files/Haibike-AllTrack-6-2026-Electric-Bike.jpg?v=1765897424",
      "url": "https://www.e-bikeshop.co.uk/products/electric-bike-haibike-alltrack-6-2026",
      "badge_text": "SAVE £450 (15% OFF)"
    },
    {
      "id": "velotric_7296176488631",
      "title": "Velotric T1 ST Plus Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Commuter",
      "dealBucket": "Standard Deal",
      "dealScore": 22.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1649,
      "sale_price": 1299,
      "savings_amount": 350,
      "discount_percentage": 21,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/T1ST_plus_lava_right_side_1_1_1.png?v=1764064119",
      "url": "https://www.velotricbike.com/products/velotric-t1st-ebike",
      "badge_text": "SAVE $350 (21% OFF)"
    },
    {
      "id": "engwe_uk_8815718695094",
      "title": "O20 Boost Combo",
      "brand": "ENGWE UK Official",
      "retailer": "Engwe UK Official",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Cargo & Fat Tyre",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 21.8,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 2348,
      "sale_price": 1948,
      "savings_amount": 400,
      "discount_percentage": 17,
      "image": "https://cdn.shopify.com/s/files/1/0627/1385/6182/files/c0ad2be69190712bf2cde8f7cd4fee95.jpg?v=1782697074",
      "url": "https://engwe-bikes-uk.com/products/engwe-o20-boost-combo",
      "badge_text": "SAVE £400 (17% OFF)"
    },
    {
      "id": "pure_electric_14937652167032",
      "title": "Air⁵ Ultra Suspension",
      "brand": "Pure Electric",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 21.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 699,
      "sale_price": 499,
      "savings_amount": 200,
      "discount_percentage": 29,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-electric-scooter-air-ultra-suspension-1238469011.jpg?v=1778803545",
      "url": "https://www.pureelectric.com/products/air5-ultra-suspension",
      "badge_text": "SAVE £200 (29% OFF)"
    },
    {
      "id": "e_bikeshop_co_uk_15363973841280",
      "title": "Haibike AllTrack 4 2026",
      "brand": "Haibike Electric Bikes",
      "retailer": "E-BikeShop UK",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Mountain",
      "dealBucket": "🔥 Mega Deal",
      "dealScore": 20.8,
      "motor_power": "250W-500W High Torque",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 2599,
      "sale_price": 2199,
      "savings_amount": 400,
      "discount_percentage": 15,
      "image": "https://cdn.shopify.com/s/files/1/0609/4838/1934/files/Haibike-AllTrack-4-2026-Electric-Bike.jpg?v=1765899542",
      "url": "https://www.e-bikeshop.co.uk/products/electric-bike-haibike-alltrack-4-2026",
      "badge_text": "SAVE £400 (15% OFF)"
    },
    {
      "id": "pure_electric_14904608751992",
      "title": "Advance+ Reboxed",
      "brand": "Pure",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 20.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 749,
      "sale_price": 549,
      "savings_amount": 200,
      "discount_percentage": 27,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-scooter-platinum-advance-33049019514968.jpg?v=1720747281",
      "url": "https://www.pureelectric.com/products/advance-reboxed-1",
      "badge_text": "SAVE £200 (27% OFF)"
    },
    {
      "id": "pure_electric_14932006240632",
      "title": "Escape Pro (Previous Gen)",
      "brand": "Pure Electric",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 18.5,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 549,
      "sale_price": 399,
      "savings_amount": 150,
      "discount_percentage": 27,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-electric-scooter-escape-pro-1238462108.jpg?v=1778800600",
      "url": "https://www.pureelectric.com/products/escape-pro",
      "badge_text": "SAVE £150 (27% OFF)"
    },
    {
      "id": "pure_electric_15020411683192",
      "title": "Pure x McLaren Black Refurbished",
      "brand": "Pure",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 17.7,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 899,
      "sale_price": 699,
      "savings_amount": 200,
      "discount_percentage": 22,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-scooter-black-pure-x-mclaren-black-1230822866.jpg?v=1775044030",
      "url": "https://www.pureelectric.com/products/pure-x-mclaren-black-refurbished",
      "badge_text": "SAVE £200 (22% OFF)"
    },
    {
      "id": "pure_electric_15020411519352",
      "title": "Pure x McLaren Papaya Refurbished",
      "brand": "Pure",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 17.7,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 899,
      "sale_price": 699,
      "savings_amount": 200,
      "discount_percentage": 22,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-scooter-papaya-pure-x-mclaren-papaya-1230798400.jpg?v=1775035570",
      "url": "https://www.pureelectric.com/products/pure-x-mclaren-papaya-refurbished",
      "badge_text": "SAVE £200 (22% OFF)"
    },
    {
      "id": "velotric_7525259346103",
      "title": "Velotric Discover 2 Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Commuter",
      "dealBucket": "Standard Deal",
      "dealScore": 17.5,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1999,
      "sale_price": 1699,
      "savings_amount": 300,
      "discount_percentage": 15,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/Discover_2-Cherry_Crimson_right_side_1_1_1.png?v=1781150053",
      "url": "https://www.velotricbike.com/products/velotric-discover-2",
      "badge_text": "SAVE $300 (15% OFF)"
    },
    {
      "id": "velotric_15010086617460",
      "title": "Velotric GoMad Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Cargo & Fat Tyre",
      "dealBucket": "Standard Deal",
      "dealScore": 15.5,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 2283.99,
      "sale_price": 1999,
      "savings_amount": 285,
      "discount_percentage": 12,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/GoMad_Dark_Amber_right_side_1_1_1.png?v=1775118888",
      "url": "https://www.velotricbike.com/products/velotric-gomad-utility-ebike",
      "badge_text": "SAVE $285 (12% OFF)"
    },
    {
      "id": "engwe_uk_8269327138998",
      "title": "EP-2 3.0 Boost",
      "brand": "engwe uk",
      "retailer": "Engwe UK Official",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "Standard Deal",
      "dealScore": 14.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 1299,
      "sale_price": 1099,
      "savings_amount": 200,
      "discount_percentage": 15,
      "image": "https://cdn.shopify.com/s/files/1/0627/1385/6182/files/EP-23.0boost01.jpg?v=1767084299",
      "url": "https://engwe-bikes-uk.com/products/engwe-ep-2-3-0-boost",
      "badge_text": "SAVE £200 (15% OFF)"
    },
    {
      "id": "velotric_7528742715575",
      "title": "Velotric Summit 1 Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Commuter",
      "dealBucket": "Standard Deal",
      "dealScore": 11.7,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1999,
      "sale_price": 1799,
      "savings_amount": 200,
      "discount_percentage": 10,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/S1_SunriseOrange_rightside_L_1_1.png?v=1712653090",
      "url": "https://www.velotricbike.com/products/velotric-summit-1",
      "badge_text": "SAVE $200 (10% OFF)"
    },
    {
      "id": "tenways_14923430789492",
      "title": "TENWAYS AGO X",
      "brand": "TENWAYS",
      "retailer": "Tenways Global",
      "country": "EU/UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "Standard Deal",
      "dealScore": 10.8,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1744,
      "sale_price": 1570,
      "savings_amount": 174,
      "discount_percentage": 10,
      "image": "https://cdn.shopify.com/s/files/1/0563/3926/7733/files/26-green-1_91a6bb82-d699-4ec2-9d2b-693692afc7be.webp?v=1772448584",
      "url": "https://www.tenways.com/products/ago-x",
      "badge_text": "SAVE £174 (10% OFF)"
    },
    {
      "id": "pure_electric_14955809997176",
      "title": "Pure x McLaren Chrome Reboxed",
      "brand": "Pure",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 9.8,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 799,
      "sale_price": 699,
      "savings_amount": 100,
      "discount_percentage": 13,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-scooter-chrome-pure-x-mclaren-chrome-1182624359.jpg?v=1754076717",
      "url": "https://www.pureelectric.com/products/pure-x-mclaren-chrome-reboxed",
      "badge_text": "SAVE £100 (13% OFF)"
    },
    {
      "id": "velotric_14638468268404",
      "title": "Velotric Nomad 2 Fat Tire Ebike",
      "brand": "Velotric",
      "retailer": "Velotric Direct",
      "country": "US/Global",
      "currency": "USD",
      "symbol": "$",
      "category": "Cargo & Fat Tyre",
      "dealBucket": "Standard Deal",
      "dealScore": 9,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "20 mph",
      "is_uk_legal": false,
      "rrp": 1999,
      "sale_price": 1849,
      "savings_amount": 150,
      "discount_percentage": 8,
      "image": "https://cdn.shopify.com/s/files/1/0599/2094/1239/files/N2_ST_Cranberry_6db64f59-9f01-4aa7-b9e2-11b8b33337f8.png?v=1739432018",
      "url": "https://www.velotricbike.com/products/velotric-nomad-2",
      "badge_text": "SAVE $150 (8% OFF)"
    },
    {
      "id": "pure_electric_14941317824888",
      "title": "Pure x McLaren Flex",
      "brand": "Pure",
      "retailer": "Pure Electric",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 8.3,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 999,
      "sale_price": 899,
      "savings_amount": 100,
      "discount_percentage": 10,
      "image": "https://cdn.shopify.com/s/files/1/0063/2714/0425/files/pure-scooter-papaya-pure-x-mclaren-flex-1238469007.jpg?v=1778803486",
      "url": "https://www.pureelectric.com/products/pure-x-mclaren-flex",
      "badge_text": "SAVE £100 (10% OFF)"
    },
    {
      "id": "engwe_uk_8183413309622",
      "title": "EP-2 Boost",
      "brand": "Engwe-bikes-UK",
      "retailer": "Engwe UK Official",
      "country": "UK",
      "currency": "GBP",
      "symbol": "£",
      "category": "Commuter",
      "dealBucket": "⚡ Budget Steal",
      "dealScore": 4.2,
      "motor_power": "250W Road Legal",
      "battery": "400Wh - 750Wh Lithium-Ion",
      "range_miles": "35 - 75 Miles",
      "max_speed": "15.5 mph",
      "is_uk_legal": true,
      "rrp": 949,
      "sale_price": 899,
      "savings_amount": 50,
      "discount_percentage": 5,
      "image": "https://cdn.shopify.com/s/files/1/0627/1385/6182/files/2_f7000d51-73b1-442e-9190-8c7e25f9bf48.jpg?v=1767074687",
      "url": "https://engwe-bikes-uk.com/products/engwe-ep-2-boost",
      "badge_text": "SAVE £50 (5% OFF)"
    }
  ]
};